###
POST http://localhost:3000/notifications/new
Content-Type: application/json

    {
        "message": "New test message",
        "recipient": "user@gmail.com",
        "time": "08/04/2018 12:00",
        "unread": false
    }

###
GET http://localhost:3000/notifications
Content-Type: application/json