###
POST http://localhost:3000/notifications/new
Content-Type: application/json

    {
        "message": "XXX03",
        "recipient": "user@gmail.com",
        "time": "08/04/2018 12:00",
        "unread": false
    }

###
GET http://localhost:3000/notifications/
Content-Type: application/json

###
GET http://localhost:3000/notifications/5b51844a6601e3458483f8f3
Content-Type: application/json

###
PATCH http://localhost:3000/notifications/5b518f2c86236a473687ed16
Content-Type: application/json

    {
        "message": "XXX02",
        "recipient": "user@gmail.com",
        "time": "08/04/2018 12:10",
        "unread": false
    }
