###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
  "email": "example@gmail.com",
  "password": "password"
}

###
PATCH http://localhost:3000/users/5b56b47306610268e19c5261
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNTMyNDA5MDM3fQ.8lo1N2rqJExpWyD7ayqQWBvPxhkY7Ubtrqva25RBZLc; Path=/; HttpOnly
Content-Type: application/json


{
        "role": "facilitator",
        "f_name": "Sveto",
        "l_name": "Stojcevic",
        "contact_no": "0466 558 571",
        "default_location": "220 Spenser St",
        "availability": true,
        "longitude": 0,
        "Latitude": 0,
        "skills": []
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
     "email": "test1@gmail.com",
        "password": "1234567",
        "role": "facilitator",
        "f_name": "Joel",
        "l_name": "Simons",
        "contact_no": "0466 558 570",
        "default_location": "120 Spenser",
        "availability": true,
        "longitude": 0,
        "Latitude": 0
}

