###
POST http://localhost:3001/auth/login
Content-Type: application/json 

{
  "email": "example1@gmail.com",
  "password": "password"
}

###
PATCH http://localhost:3001/users/5b56c3aebc37e06f54e0a8ac
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQGdtYWlsLmNvbSIsImlhdCI6MTUzMjQxNTYxMX0.zvcbgO9zRK1UnBnhpqM8j_N8q7zPKkR6eR7B0v79LnY; Path=/; HttpOnly
Content-Type: application/json


{
        "role": "facilitator",
        "f_name": "Gen",
        "l_name": "Mauger",
        "contact_no": "0466 558 571",
        "default_location": "220 Spencer St",
        "availability": true,
        "longitude": 0,
        "Latitude": 0,
        "skills": []
}

###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
     "email": "test1@gmail.com",
        "password": "1234567",
        "role": "facilitator",
        "f_name": "Joel",
        "l_name": "Simons",
        "contact_no": "0466 558 570",
        "default_location": "120 Spenser",
        "availability": true,
        "longitude": 0,
        "Latitude": 0
}

