###
POST http://localhost:3000/items/new
Content-Type: application/json

{
    "title": "XXXXX",
    "facilitators": "Tyson Butler-Boschma ",
    "attendees": 0,
    "status": "Pending",
    "creator": null,
    "notes": "XXXXX DATA",
    "onsite": true,
    "price": 55000,
    "organisation": "CA Mel",
    "bookings": []
}

###
PUT http://localhost:3000/items/5b4b5f2c9f7c610867b5505f/new
Content-Type: application/json

            {
                "start": "12/23/2018 10:00",
                "end": "12/23/2018 13:00",
                "location": "Room 1212"
            }

###
PUT http://localhost:3000/items/5b4b5f2c9f7c610867b5505f/5b4b5ff9be59fe088ec33d71/remove
Content-Type: application/json