###
POST http://localhost:3000/workshops/new
Content-Type: application/json

{
    "title": "XXXXX",
    "facilitators": "Tyson Butler-Boschma ",
    "attendees": 0,
    "status": "Pending",
    "creator": null,
    "notes": "XXXXX DATA",
    "onsite": true,
    "price": 55000,
    "organisation": "CA Mel",
    "bookings": []
}

###
PUT http://localhost:3000/workshops/5b4b3a0f6f767c048107a63c/new
Content-Type: application/json

            {
                "start": "12/12/2018 10:00",
                "end": "12/12/2018 13:00",
                "location": "Room 1212"
            }

###
PUT http://localhost:3000/workshops/5b4b3a0f6f767c048107a63c/5b4b3a316f767c048107a63f/remove
Content-Type: application/json